name: flutter_snippets
description: A new Flutter project.
publish_to: 'none'
version: 1.2.0+4

environment:
  sdk: ">=2.14.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.3
  intl: ^0.17.0
  font_awesome_flutter: ^9.1.0
  url_launcher: ^6.0.10
  firebase_core: ^1.6.0
  cloud_firestore: ^2.5.2 
  badges: ^2.0.1
  readmore: ^2.1.0    
  package_info_plus: ^1.0.6  
  provider: ^6.0.0
  shared_preferences: ^2.0.7
  flutter_launcher_icons: ^0.9.2

dev_dependencies:
  flutter_lints: ^1.0.4
  flutter_test:
    sdk: flutter

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/snippets/
    - assets/images/
    - assets/json/
    - assets/txt/

  fonts:
    - family: OpenSans
      fonts:
        - asset: assets/fonts/OpenSans-Regular.ttf

flutter_icons:
  android: true
  ios: true
  image_path: assets/images/icon_flutter_snippets.png     